version: "3"
networks:
  nocobase:
    driver: bridge
services:
  adminer:
    image: adminer
    restart: always
    networks:
      - nocobase
    ports:
      - ${ADMINER_PORT}:8080
  postgres:
    image: postgres:10
    restart: always
    networks:
      - nocobase
    command: postgres -c wal_level=logical
    volumes:
      - ./backups/postgres:/backups
      - ./database/postgres:/var/lib/postgresql/data
    #ports:
    #  - ${DB_POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - nocobase
    command: [ "yarn", "start" ]
    working_dir: /app
    env_file: ./.env
    volumes:
      - ./app:/app
    expose:
      - 8000
    ports:
      - "${APP_PORT}:8000"
